---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04
    driver:
      box: trusty-server-cloudimg-amd64-vagrant-disk1
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: default
    run_list:
      - recipe[pw_base::default]
      - recipe[pw_base::ssh-user]
      - recipe[pw_base::gemrc]
    attributes:
      pw_base:
        domain: 'test01.prod.pingworks.ws.net'
        dns: '10.33.0.10'
        gemrc-files:
          - '/opt/chef/embedded/etc/gemrc'
